"""create model_metadata table

Revision ID: 5c5dace0df8b
Revises:
Create Date: 2026-04-24 21:27:43.586494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c5dace0df8b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("series_id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("mlflow_run_id", sa.String(), nullable=False),
        sa.Column("points_used", sa.Integer(), nullable=False),
        sa.Column(
            "trained_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mlflow_run_id"),
    )
    op.create_index(
        op.f("ix_model_metadata_series_id"),
        "model_metadata",
        ["series_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_metadata_series_id"), table_name="model_metadata")
    op.drop_table("model_metadata")
    # ### end Alembic commands ###
